# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## Base settings ##
url: "https://blog.6941.tech/" #The site's Protocol and Hostname e.g. https://blog.someone.com (!!required!!)
title: 6941 | IronPulse
description: > #this means to ignore newlines until "base_path:"
    6941 | IronPulse

##* Home base settings ##
baseurl: "/"
avata_url: https://wx3.sinaimg.cn/large/73bd9e13ly1fjkqy66hl8j208c08c0td.jpg

##* Blog base settings ##
blog:
  baseurl: "/blog"
  title: IronPulse | Tutorials
  description: IronPulse | Tutorials
  nav_lists:
    - title: About
      url: /blog/about.html
##* Artsworks base settings ##
artworks:
  baseurl: ""

## GitHub repository (if the site is hosted by GitHub) ##
repository: TheInvidia/theinvidia.github.io
repository_tree: master

## Language & timezone ##
lang: zh # the language of your site
timezone: Asia/Shanghai

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false
